<?php
			if(isset($_POST['signup']))
			{
				$singup_result=$user->user_register($_POST['name'],$_POST['lastname'],$_POST['stanowisko'],$_POST['udo'],$_POST['email'],$_POST['login'],$_POST['password']);
				if($singup_result['stan']=='true'){
						header('Location:'.PATH.'users,ok');
				}
				else
				{
					$smarty->assign('feedback',$singup_result);
				}
			}
?>